typography_spectrum: 0.8899033
color:
  saturation: 0.6498120771721005
  brandStrength: 0.1149700907990336
  rhythmicContrast: 0.3598095432389528
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  lightness: 0.98595687514171
layout_spectrum: 1
name: avatar
navigation:
  - name: What is Avatar?
    id: 7c82fcc4-a462-4eea-9e4a-b6215e660fb9
    type: content
  - name: Section 1 - Resurfacing
    id: 65a22f83-aaa1-4654-bb63-71eb3e6fb515
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Avatar for the City
description: 'A Smart, Experiential Deep Dive into Consciousness'
