layout_spectrum: 0.25551082333549857
typography_spectrum: 0.953261497663334
color:
  brandStrength: 0.11497009079903364
  lightness: 0.98595687514171
  saturation: 0.6498120771721005
  rhythmicContrast: 0.35980954323895276
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
name: avatar
navigation:
  - id: 7c82fcc4-a462-4eea-9e4a-b6215e660fb9
    url: 2016-07-24-what-is-avatar.html
    name: What is Avatar?
    type: content
  - id: 65a22f83-aaa1-4654-bb63-71eb3e6fb515
    url: 2016-07-24-section-1-resurfacing.html
    name: Section 1 - Resurfacing
    type: content
  - id: 'http://onespiritinterfaith.org/'
    url: 'http://onespiritinterfaith.org/'
    name: One Spirit
    type: external
